// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boztpjagqdiaicubhkxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvenRwamFncWRpYWljdWJoa3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjU1MzUsImV4cCI6MjA2MjAwMTUzNX0.T5NPnpvMhnHBlJmT1lffEj5vWeXU6nKaiv1LrsYcqoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);